# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 400)
        MainWindow.setMinimumSize(QtCore.QSize(550, 400))
        MainWindow.setMaximumSize(QtCore.QSize(650, 588))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(650, 588))
        self.centralwidget.setMaximumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QFrame(self.centralwidget)
        self.titulo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titulo.setStyleSheet("background-color:rgb(13, 9, 22)")
        self.titulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(self.titulo)
        self.label.setGeometry(QtCore.QRect(200, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"color: rgb(182, 182, 182);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.titulo)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#ffff00")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.titulo)
        self.corpo = QtWidgets.QFrame(self.centralwidget)
        self.corpo.setStyleSheet("background-color:rgb(13, 13, 24)")
        self.corpo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.corpo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.corpo.setObjectName("corpo")
        self.menus = QtWidgets.QFrame(self.corpo)
        self.menus.setGeometry(QtCore.QRect(0, 0, 101, 361))
        self.menus.setStyleSheet("background-color:rgb(13,9,22)")
        self.menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menus.setObjectName("menus")
        self.botao1 = QtWidgets.QPushButton(self.menus)
        self.botao1.setGeometry(QtCore.QRect(0, 0, 101, 72))
        self.botao1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao1.setObjectName("botao1")
        self.botao2 = QtWidgets.QPushButton(self.menus)
        self.botao2.setGeometry(QtCore.QRect(0, 70, 101, 72))
        self.botao2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao2.setObjectName("botao2")
        self.botao3 = QtWidgets.QPushButton(self.menus)
        self.botao3.setGeometry(QtCore.QRect(0, 140, 101, 72))
        self.botao3.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao3.setObjectName("botao3")
        self.botao4 = QtWidgets.QPushButton(self.menus)
        self.botao4.setGeometry(QtCore.QRect(0, 210, 101, 72))
        self.botao4.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4.setObjectName("botao4")
        self.botao5 = QtWidgets.QPushButton(self.menus)
        self.botao5.setGeometry(QtCore.QRect(0, 280, 101, 72))
        self.botao5.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao5.setObjectName("botao5")
        self.TELAS = QtWidgets.QStackedWidget(self.corpo)
        self.TELAS.setGeometry(QtCore.QRect(100, 0, 451, 361))
        self.TELAS.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.TELAS.setObjectName("TELAS")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.frame = QtWidgets.QFrame(self.page1)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 291, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_2.setContentsMargins(0, 0, 3, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:#FFF")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setStyleSheet("background-color:#fff")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:#FFF")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_9.setStyleSheet("background-color:#fff\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.botao4_5 = QtWidgets.QPushButton(self.layoutWidget)
        self.botao4_5.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4_5.setObjectName("botao4_5")
        self.gridLayout_2.addWidget(self.botao4_5, 2, 1, 1, 1)
        self.TELAS.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.frame_2 = QtWidgets.QFrame(self.page2)
        self.frame_2.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.TELAS.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.frame_3 = QtWidgets.QFrame(self.page3)
        self.frame_3.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(70, 110, 291, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_3.setContentsMargins(0, 0, 3, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color:#FFF")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_10.setStyleSheet("background-color:#fff")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_3.addWidget(self.lineEdit_10, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:#FFF")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_11.setStyleSheet("background-color:#fff\n"
"")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 1, 1, 1, 1)
        self.botao4_6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.botao4_6.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4_6.setObjectName("botao4_6")
        self.gridLayout_3.addWidget(self.botao4_6, 2, 1, 1, 1)
        self.TELAS.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.frame_4 = QtWidgets.QFrame(self.page4)
        self.frame_4.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.TELAS.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.frame_5 = QtWidgets.QFrame(self.page5)
        self.frame_5.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.TELAS.addWidget(self.page5)
        self.verticalLayout.addWidget(self.corpo)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONTROLADOR DE EVENTOS"))
        self.label_2.setText(_translate("MainWindow", "MENU"))
        self.botao1.setText(_translate("MainWindow", "CADASTRAR \n"
"PARTICIPANTES"))
        self.botao2.setText(_translate("MainWindow", "CONSULTAR \n"
"PARTICIPANTES"))
        self.botao3.setText(_translate("MainWindow", "CADASTRAR\n"
"SALAS"))
        self.botao4.setText(_translate("MainWindow", "CONSULTAR\n"
"SALAS"))
        self.botao5.setText(_translate("MainWindow", "INFORMAÇÕES\n"
"GERAIS"))
        self.label_11.setText(_translate("MainWindow", "NOME:"))
        self.label_12.setText(_translate("MainWindow", "SOBRENOME:"))
        self.botao4_5.setText(_translate("MainWindow", "REGISTAR"))
        self.label_13.setText(_translate("MainWindow", "NOME:"))
        self.label_14.setText(_translate("MainWindow", "SOBRENOME:"))
        self.botao4_6.setText(_translate("MainWindow", "REGISTAR"))
