# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 400)
        MainWindow.setMinimumSize(QtCore.QSize(550, 400))
        MainWindow.setMaximumSize(QtCore.QSize(650, 588))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(650, 588))
        self.centralwidget.setMaximumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QFrame(self.centralwidget)
        self.titulo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titulo.setStyleSheet("background-color:rgb(13, 9, 22)")
        self.titulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(self.titulo)
        self.label.setGeometry(QtCore.QRect(200, 10, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"color: rgb(182, 182, 182);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.titulo)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#ffff00")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.titulo)
        self.corpo = QtWidgets.QFrame(self.centralwidget)
        self.corpo.setStyleSheet("background-color:rgb(13, 13, 24)")
        self.corpo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.corpo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.corpo.setObjectName("corpo")
        self.menus = QtWidgets.QFrame(self.corpo)
        self.menus.setGeometry(QtCore.QRect(0, 0, 101, 361))
        self.menus.setStyleSheet("background-color:rgb(13,9,22)")
        self.menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menus.setObjectName("menus")
        self.botao2 = QtWidgets.QPushButton(self.menus)
        self.botao2.setGeometry(QtCore.QRect(0, 150, 101, 72))
        self.botao2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}\n"
"QPushButton:hover:enabled\n"
"{\n"
"  border: 1px solid red;\n"
"}")
        self.botao2.setObjectName("botao2")
        self.botao3 = QtWidgets.QPushButton(self.menus)
        self.botao3.setGeometry(QtCore.QRect(0, 0, 101, 72))
        self.botao3.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao3.setObjectName("botao3")
        self.botao4 = QtWidgets.QPushButton(self.menus)
        self.botao4.setGeometry(QtCore.QRect(0, 220, 101, 72))
        self.botao4.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4.setObjectName("botao4")
        self.botao5 = QtWidgets.QPushButton(self.menus)
        self.botao5.setGeometry(QtCore.QRect(0, 280, 101, 72))
        self.botao5.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao5.setObjectName("botao5")
        self.botao1 = QtWidgets.QPushButton(self.menus)
        self.botao1.setGeometry(QtCore.QRect(0, 70, 101, 72))
        self.botao1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao1.setObjectName("botao1")
        self.TELAS = QtWidgets.QStackedWidget(self.corpo)
        self.TELAS.setGeometry(QtCore.QRect(100, 0, 451, 361))
        self.TELAS.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.TELAS.setObjectName("TELAS")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.frame = QtWidgets.QFrame(self.page1)
        self.frame.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.botao4_5 = QtWidgets.QPushButton(self.frame)
        self.botao4_5.setGeometry(QtCore.QRect(130, 180, 196, 15))
        self.botao4_5.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4_5.setObjectName("botao4_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 98, 196, 20))
        self.lineEdit_8.setStyleSheet("background-color:#fff")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(130, 139, 196, 20))
        self.lineEdit_9.setStyleSheet("background-color:#fff\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(39, 98, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:#FFF")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(39, 139, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:#FFF")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(30, 200, 361, 121))
        self.textEdit.setStyleSheet("color:#FFF")
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Cyberpunk")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(250, 250, 0)")
        self.label_6.setObjectName("label_6")
        self.TELAS.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.frame_2 = QtWidgets.QFrame(self.page2)
        self.frame_2.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(-1)
        self.frame_2.setObjectName("frame_2")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(160, 100, 196, 20))
        self.lineEdit_12.setStyleSheet("background-color:#fff")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.botao4_7 = QtWidgets.QPushButton(self.frame_2)
        self.botao4_7.setGeometry(QtCore.QRect(160, 140, 196, 31))
        self.botao4_7.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4_7.setObjectName("botao4_7")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_13.setGeometry(QtCore.QRect(160, 60, 196, 20))
        self.lineEdit_13.setStyleSheet("background-color:#fff")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(60, 100, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:#FFF")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(60, 60, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:#FFF")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.textEdit_4 = QtWidgets.QTextEdit(self.frame_2)
        self.textEdit_4.setGeometry(QtCore.QRect(50, 190, 311, 31))
        self.textEdit_4.setLineWidth(0)
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 0, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Cyberpunk")
        font.setPointSize(19)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(250, 250, 0)")
        self.label_7.setObjectName("label_7")
        self.TELAS.addWidget(self.page2)
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        self.frame_3 = QtWidgets.QFrame(self.page3)
        self.frame_3.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setGeometry(QtCore.QRect(20, 50, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color:#FFF")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_2.setGeometry(QtCore.QRect(110, 50, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color:#FFF")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_3.setGeometry(QtCore.QRect(190, 50, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color:#FFF")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_4.setGeometry(QtCore.QRect(310, 50, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("color:#FFF")
        self.radioButton_4.setObjectName("radioButton_4")
        self.botao4_6 = QtWidgets.QPushButton(self.frame_3)
        self.botao4_6.setGeometry(QtCore.QRect(160, 120, 111, 31))
        self.botao4_6.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4_6.setObjectName("botao4_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit_3.setGeometry(QtCore.QRect(40, 170, 351, 121))
        self.textEdit_3.setStyleSheet("color:#FFF")
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(50, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:#FFF")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(130, 90, 158, 20))
        self.lineEdit_11.setStyleSheet("background-color:#fff\n"
"")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(40, -10, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cyberpunk")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(250, 250, 0)")
        self.label_5.setObjectName("label_5")
        self.TELAS.addWidget(self.page3)
        self.page4 = QtWidgets.QWidget()
        self.page4.setObjectName("page4")
        self.frame_4 = QtWidgets.QFrame(self.page4)
        self.frame_4.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.botao4_8 = QtWidgets.QPushButton(self.frame_4)
        self.botao4_8.setGeometry(QtCore.QRect(110, 60, 196, 31))
        self.botao4_8.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4_8.setObjectName("botao4_8")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_4)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 110, 341, 221))
        self.textEdit_2.setObjectName("textEdit_2")
        self.layoutWidget = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 318, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_5.setStyleSheet("COLOR:#fff")
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_6.setStyleSheet("COLOR:#fff")
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_7.setStyleSheet("COLOR:#fff")
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_8.setStyleSheet("COLOR:#fff")
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout.addWidget(self.radioButton_8)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(40, -20, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cyberpunk")
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(250, 250, 0)")
        self.label_8.setObjectName("label_8")
        self.TELAS.addWidget(self.page4)
        self.page5 = QtWidgets.QWidget()
        self.page5.setObjectName("page5")
        self.frame_5 = QtWidgets.QFrame(self.page5)
        self.frame_5.setGeometry(QtCore.QRect(-1, -1, 451, 361))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.botao4_9 = QtWidgets.QPushButton(self.frame_5)
        self.botao4_9.setGeometry(QtCore.QRect(140, 310, 151, 31))
        self.botao4_9.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4_9.setObjectName("botao4_9")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#FFF")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setLineWidth(8)
        self.label_3.setMidLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 40, 431, 191))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(50, -10, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Cyberpunk")
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(250, 250, 0)")
        self.label_9.setObjectName("label_9")
        self.TELAS.addWidget(self.page5)
        self.verticalLayout.addWidget(self.corpo)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONTROLADOR DE EVENTOS"))
        self.label_2.setText(_translate("MainWindow", "MENU"))
        self.botao2.setText(_translate("MainWindow", "CONSULTAR \n"
"PARTICIPANTES"))
        self.botao3.setText(_translate("MainWindow", "CADASTRAR\n"
"SALAS"))
        self.botao4.setText(_translate("MainWindow", "CONSULTAR\n"
"SALAS"))
        self.botao5.setText(_translate("MainWindow", "INFORMAÇÕES\n"
"GERAIS"))
        self.botao1.setText(_translate("MainWindow", "CADASTRAR \n"
"PARTICIPANTES"))
        self.botao4_5.setText(_translate("MainWindow", "REGISTAR"))
        self.label_11.setText(_translate("MainWindow", "NOME:"))
        self.label_12.setText(_translate("MainWindow", "SOBRENOME:"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Cadatrar Participantes"))
        self.botao4_7.setText(_translate("MainWindow", "CONSULTAR"))
        self.label_15.setText(_translate("MainWindow", "SOBRENOME"))
        self.label_16.setText(_translate("MainWindow", "NOME:"))
        self.label_7.setText(_translate("MainWindow", "Consultar Participantes"))
        self.radioButton.setText(_translate("MainWindow", "SALA 1"))
        self.radioButton_2.setText(_translate("MainWindow", "SALA 2"))
        self.radioButton_3.setText(_translate("MainWindow", "SALA DE CAFÉ"))
        self.radioButton_4.setText(_translate("MainWindow", "SALA DE CAFÉ 2"))
        self.botao4_6.setText(_translate("MainWindow", "REGISTAR"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "LOTAÇÃO:"))
        self.label_5.setText(_translate("MainWindow", "Cadastrar Salas"))
        self.botao4_8.setText(_translate("MainWindow", "CONSULTAR"))
        self.radioButton_5.setText(_translate("MainWindow", "SALA 1"))
        self.radioButton_6.setText(_translate("MainWindow", "SALA 2"))
        self.radioButton_7.setText(_translate("MainWindow", "SALA_CAFÉ_1"))
        self.radioButton_8.setText(_translate("MainWindow", "SALA_CAFÉ_2"))
        self.label_8.setText(_translate("MainWindow", "Consultar Salas"))
        self.botao4_9.setText(_translate("MainWindow", "SWITCH"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:8pt;\">Para estimular a troca de conhecimentos, metade das pessoas </span></p><p align=\"justify\"><span style=\" font-size:8pt;\">precisam trocar de sala entre as duas etapas do treinamento.</span></p><p align=\"justify\"><span style=\" font-size:8pt;\">Para fazer essa troca basta pressionar o botão abaixo:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Projects. Info"))
