# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 400)
        MainWindow.setMinimumSize(QtCore.QSize(550, 400))
        MainWindow.setMaximumSize(QtCore.QSize(650, 588))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(650, 588))
        self.centralwidget.setMaximumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QFrame(self.centralwidget)
        self.titulo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.titulo.setStyleSheet("background-color:rgb(13, 9, 22)")
        self.titulo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo.setObjectName("titulo")
        self.label = QtWidgets.QLabel(self.titulo)
        self.label.setGeometry(QtCore.QRect(200, 10, 221, 20))
        self.label.setStyleSheet("color:white")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.titulo)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#ffff00")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.titulo)
        self.corpo = QtWidgets.QFrame(self.centralwidget)
        self.corpo.setStyleSheet("background-color:rgb(13, 13, 24)")
        self.corpo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.corpo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.corpo.setObjectName("corpo")
        self.menus = QtWidgets.QFrame(self.corpo)
        self.menus.setGeometry(QtCore.QRect(0, 0, 101, 361))
        self.menus.setStyleSheet("background-color:rgb(13,9,22)")
        self.menus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menus.setObjectName("menus")
        self.botao1 = QtWidgets.QPushButton(self.menus)
        self.botao1.setGeometry(QtCore.QRect(0, 0, 101, 72))
        self.botao1.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao1.setObjectName("botao1")
        self.botao2 = QtWidgets.QPushButton(self.menus)
        self.botao2.setGeometry(QtCore.QRect(0, 70, 101, 72))
        self.botao2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao2.setObjectName("botao2")
        self.botao3 = QtWidgets.QPushButton(self.menus)
        self.botao3.setGeometry(QtCore.QRect(0, 140, 101, 72))
        self.botao3.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao3.setObjectName("botao3")
        self.botao4 = QtWidgets.QPushButton(self.menus)
        self.botao4.setGeometry(QtCore.QRect(0, 210, 101, 72))
        self.botao4.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao4.setObjectName("botao4")
        self.botao5 = QtWidgets.QPushButton(self.menus)
        self.botao5.setGeometry(QtCore.QRect(0, 280, 101, 72))
        self.botao5.setStyleSheet("QPushButton{\n"
"    background-color:rgb(13, 9, 22);\n"
"    color:white;\n"
"    border:1px solid;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,255,0);\n"
"    color:black;\n"
"}")
        self.botao5.setObjectName("botao5")
        self.TELAS = QtWidgets.QStackedWidget(self.corpo)
        self.TELAS.setGeometry(QtCore.QRect(100, 0, 451, 361))
        self.TELAS.setObjectName("TELAS")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.label_3 = QtWidgets.QLabel(self.page1)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 461, 371))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.TELAS.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.label_4 = QtWidgets.QLabel(self.page2)
        self.label_4.setGeometry(QtCore.QRect(10, 0, 441, 351))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.TELAS.addWidget(self.page2)
        self.verticalLayout.addWidget(self.corpo)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CONTROLADOR DE EVENTOS"))
        self.label_2.setText(_translate("MainWindow", "MENU"))
        self.botao1.setText(_translate("MainWindow", "CADASTRAR \n"
"PARTICIPANTES"))
        self.botao2.setText(_translate("MainWindow", "CONSULTAR \n"
"PARTICIPANTES"))
        self.botao3.setText(_translate("MainWindow", "CONSULTAR\n"
"SALAS"))
        self.botao4.setText(_translate("MainWindow", "CONSULTAR\n"
" PARTICIPANTES"))
        self.botao5.setText(_translate("MainWindow", "INFORMAÇÕES\n"
"GERAIS"))
        self.label_3.setText(_translate("MainWindow", "CADASTRAR PARTICIPANTES"))
        self.label_4.setText(_translate("MainWindow", "CONSULTAR PARTICIPANTES"))
